# Generated by Django 5.1.3 on 2024-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='trailer',
            field=models.URLField(null=True, verbose_name='укажите ссылку трейлера фильма'),
        ),
    ]
